// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixlrjrwdrvnqqecgbfzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4bHJqcndkcnZucXFlY2diZnpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMDc3OTksImV4cCI6MjA1ODU4Mzc5OX0.A5oRDYxi_piE8qqHK-GtI1wcTptnhjH0wr8gffcY8GY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);